service: probot-home-assistant

provider:
  name: aws
  region: us-east-1
  timeout: 10
  memorySize: 192
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x

functions:
  handleProbot:
    handler: dist/serverless_handler.probot
    exclude:
      - .devcontainer/**
    events:
      - http: POST github_probot_webhook
    environment:
      APP_ID: ${env:APP_ID}
      WEBHOOK_SECRET: ${env:APP_WEBHOOK_SECRET}
