service: probot-home-assistant

custom: ${file(config.yml)}

provider:
  name: aws
  region: us-east-1
  timeout: 10
  memorySize: 192
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x

functions:
  handleProbot:
    handler: dist/serverless_handler.probot
    exclude:
      - .devcontainer/**
    events:
      - http: POST github_probot_webhook
    environment:
      APP_ID: ${self:custom.${self:provider.stage}.github_app_id}
      WEBHOOK_SECRET: ${self:custom.${self:provider.stage}.github_app_webhook_secret}
