name: Deploy new code

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: "14"

jobs:
  deploy:
    name: Deploy code
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-NODE_VERSION }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.node-NODE_VERSION }}

      - name: Install dependencies
        run: yarn install  --immutable

      - name: Add certificate
        run: echo "${{ secrets.BOT_CERTIFICATE }}" > ./github-app-probot-home-assistant-key.pem

      - name: Upload
        run: yarn run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
