name: "Test"

on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: "14"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Test build
        run: yarn build

      - name: Test package
        run: ./node_modules/.bin/sls package
        env:
          APP_ID: "1"
          WEBHOOK_SECRET: "1"
